# -*- coding: utf-8 -*-
"""bard_task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/169DljryJYSfsmph_llu2i5McVZSi_o5w
"""

def register_user(name, email, password):
  """Registers a new user on the e-commerce platform.

  Args:
    name: The user's name.
    email: The user's email address.
    password: The user's password.

  Returns:
    True if the user was successfully registered, False otherwise.
  """

  # Validate the user's input.
  if not name or not email or not password:
    return False

  # Hash the user's password.
  hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

  # Insert the user's data into the database table.
  db = pymysql.connect(host='localhost', user='root', password='', db='ecommerce')
  cursor = db.cursor()
  cursor.execute('INSERT INTO users (name, email, password) VALUES (%s, %s, %s)', (name, email, hashed_password))
  db.commit()
  db.close()

  return True

async function registerUser() {
  const name = document.getElementById('name').value;
  const email = document.getElementById('email').value;
  const password = document.getElementById('password').value;

  const response = await fetch('/register', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name,
      email,
      password,
    }),
  });

  const data = await response.json();

  if (data.success) {
    // The user was successfully registered.
  } else {
    // The user registration failed.
  }
}