# -*- coding: utf-8 -*-
"""Gemini-task6-p2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t2mei_TMlnNaLPOVYti8pvkpthLBuneq
"""

from flask import Flask, request, redirect, flash
import sqlite3

app = Flask(__name__)

@app.route("/")
def index():
    # Show list of products with review forms
    pass

@app.route("/review/<int:product_id>", methods=["POST"])
def submit_review(product_id):
    if request.method == "POST":
        review_text = request.form["review_text"]
        rating = int(request.form["rating"])
        user_id = 1  # Replace with actual user ID
        # Sanitize user input
        review_text = "'{}'".format(review_text.replace("'", "''"))


        # Connect to database and execute query
        conn = sqlite3.connect("r.db")
        cursor = conn.cursor()
        cursor.execute("INSERT INTO reviews (user_id, product_id, review_text, score) VALUES (?, ?, ?, ?)",
                       (user_id, product_id, review_text, rating))
        conn.commit()
        conn.close()

        # Show confirmation message and redirect to product page
        flash("Review submitted successfully!", "success")
        return redirect("/product/" + str(product_id))


if __name__ == "__main__":
    app.run(debug=True)